name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * Sun'

jobs:
  create-chroot:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-unstable
          - debian-buster
          # - debian-stretch
          - ubuntu-groovy
          - ubuntu-focal
          - ubuntu-bionic
        arch:
          - amd64
          - arm64
          - armhf
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        sudo apt-get update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends sbuild schroot debootstrap ubuntu-keyring debian-archive-keyring qemu-user-static binfmt-support
    - id: build
      name: Build
      env:
        BUILD_OS: ${{matrix.os}}
        BUILD_ARCH: ${{matrix.arch}}
      run: bash ./create-chroot.sh
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-2
    - name: Upload
      env:
        ARTIFACT: ${{steps.build.outputs.artifact_path}}
      run: aws s3 cp "$ARTIFACT" s3://exapico-sbuild/
